name: image to pdf

on:
    push:
        branches: ['main', 'chore/*']
    pull_request:
        branches: ['main']

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: '3.12.7'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry install --with dev
            - name: Lint with ruff
              run: poetry run ruff check .
            - name: Type check with pyright
              run: poetry run pyright

    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.10', '3.11', '3.12']
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry install --with dev
            - name: Check for vulnerabilities
              run: poetry run pip-audit --strict || true
            - name: Test with pytest & coverage
              run: |
                  poetry run coverage run --branch --source=src -m pytest
                  poetry run coverage report -m
